// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-6WY8HDsWewTWGw0RAotnksqQq4elhU',
    appId: '1:899982208464:web:f421bb752f305f28025dd5',
    messagingSenderId: '899982208464',
    projectId: 'project-9083218032039459969',
    authDomain: 'project-9083218032039459969.firebaseapp.com',
    storageBucket: 'project-9083218032039459969.firebasestorage.app',
    measurementId: 'G-YMNPMCPYMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzMOQSLRA1bXVcasJVqqqh13x9_DT9tnA',
    appId: '1:899982208464:android:bf212754950d9186025dd5',
    messagingSenderId: '899982208464',
    projectId: 'project-9083218032039459969',
    storageBucket: 'project-9083218032039459969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv7qfZYK7NZyw_s7AAOJ0k3YZd0E8n5tQ',
    appId: '1:899982208464:ios:8fb1a831b0ba8ac2025dd5',
    messagingSenderId: '899982208464',
    projectId: 'project-9083218032039459969',
    storageBucket: 'project-9083218032039459969.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication0610',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv7qfZYK7NZyw_s7AAOJ0k3YZd0E8n5tQ',
    appId: '1:899982208464:ios:8fb1a831b0ba8ac2025dd5',
    messagingSenderId: '899982208464',
    projectId: 'project-9083218032039459969',
    storageBucket: 'project-9083218032039459969.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication0610',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0-6WY8HDsWewTWGw0RAotnksqQq4elhU',
    appId: '1:899982208464:web:1c35e6c0b833dc1b025dd5',
    messagingSenderId: '899982208464',
    projectId: 'project-9083218032039459969',
    authDomain: 'project-9083218032039459969.firebaseapp.com',
    storageBucket: 'project-9083218032039459969.firebasestorage.app',
    measurementId: 'G-W4M5KMCYPE',
  );
}
